definitions:
  v1.UserPageListReq:
    properties:
      keyword:
        type: string
      page:
        type: integer
      page_size:
        type: integer
    required:
    - page
    - page_size
    type: object
  v1.UserPageListResp:
    properties:
      id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/user/pageList:
    post:
      consumes:
      - application/json
      description: 获取用户分页列表
      parameters:
      - description: language（可选）
        in: header
        name: language
        type: string
      - description: 请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/v1.UserPageListReq'
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            items:
              $ref: '#/definitions/v1.UserPageListResp'
            type: array
      summary: 用户管理
      tags:
      - 用户
swagger: "2.0"
