app:
  name: gogo-service
  version: v1.0.0
  server:
    http:
      addr: 0.0.0.0:8001
      timeout: 1s
#    rpc:
#      addr: 0.0.0.0:9001
#      timeout: 1s
  # 服务需要加载的配置文件
  configFileNames: ['common.yaml', 'mysql.yaml', 'redis.yaml']
  serviceKV: # 应用的业务自定义配置
    authenticationKey: xxx-xxx-xx
    salt: gogo@123