name: examples-service
version: '1.0.0'
env: dev
configs:
  - ./examples/deploy/v1.0.0/db.yaml
  - ./examples/deploy/v1.0.0/logger.yaml
  - ./examples/deploy/v1.0.0/redis.yaml
server:
  http:
    addr: '0.0.0.0:8080'
    timeout: 1s
  rpc:
    addr: '0.0.0.0:9080'
    timeout: 1s
security:
  ciphertext:
    isCiphertext: false
    cipherKey: YpC5wIRf4ZuMvd4f
  jwt:
    secret: YpC5wIRf4ZuMvd4f
    issuer: bobacgo
    cacheKeyPrefix: "admin:login_token"
localCache:
  maxSize: 512MB
db:
  default:
    driver: mysql
    dryRun: false # 是否空跑 (用于调试,数据不会写入数据库)
    source: root:123456@tcp(127.0.0.1:3306)/ai_shop_user?charset=utf8mb4&parseTime=True&loc=Local
    slowThreshold: 1
    maxLifeTime: 1
    maxOpenConn: 100
    maxIdleConn: 30
  sqlite:
    driver: sqlite
    source: ./data.db
kafka:
  addrs:
    - '127.0.0.1:9092'

# 业务相关
service:
  admin:
    username: admin01
    password: admin123123
  errAttemptLimit: 5
  kafka:
    addr: '127.0.0.1:9092'
    timeout: 1s

# ====================================
# registry
registry:
  addr: '127.0.0.1:2379'