# ====================================
# logger

logger:
  level: debug                          # 可选 debug | info | error
  timeFormat: "2006-01-02 15:04:05.000"
  filepath: './logs'
  filenameSuffix: '2006-01-02-150405'
  fileExtension: log
  fileJsonEncoder: true
  fileSizeMax: 10                      # 10MB 切割文件
  fileAgeMax: 30                       # 日志保留30天
  fileCompress: true